// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel(in *jlexer.Lexer, out *ProcessContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cgroups":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v1 := 0
				for !in.IsDelim(']') {
					if v1 < 14 {
						((out.Cgroups)[v1]).UnmarshalEasyJSON(in)
						v1++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "namespace_context":
			(out.NamespaceContext).UnmarshalEasyJSON(in)
		case "credentials":
			(out.Credentials).UnmarshalEasyJSON(in)
		case "comm":
			out.Comm = string(in.String())
		case "pid":
			out.Pid = int(in.Int())
		case "tid":
			out.Tid = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel(out *jwriter.Writer, in ProcessContext) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cgroups\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v2 := range in.Cgroups {
			if v2 > 0 {
				out.RawByte(',')
			}
			((in.Cgroups)[v2]).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"namespace_context\":"
		out.RawString(prefix)
		(in.NamespaceContext).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"credentials\":"
		out.RawString(prefix)
		(in.Credentials).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"comm\":"
		out.RawString(prefix)
		out.String(string(in.Comm))
	}
	{
		const prefix string = ",\"pid\":"
		out.RawString(prefix)
		out.Int(int(in.Pid))
	}
	{
		const prefix string = ",\"tid\":"
		out.RawString(prefix)
		out.Int(int(in.Tid))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProcessContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProcessContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProcessContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProcessContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel(l, v)
}
func easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel1(in *jlexer.Lexer, out *NamespaceContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cgroup_namespace":
			out.CgroupNamespace = uint32(in.Uint32())
		case "ipc_namespace":
			out.IPCNamespace = uint32(in.Uint32())
		case "net_namespace":
			out.NetNamespace = uint32(in.Uint32())
		case "mnt_namespace":
			out.MntNamespace = uint32(in.Uint32())
		case "pid_namespace":
			out.PIDNamespace = uint32(in.Uint32())
		case "time_namespace":
			out.TimeNamespace = uint32(in.Uint32())
		case "user_namespace":
			out.UserNamespace = uint32(in.Uint32())
		case "uts_namespace":
			out.UTSNamespace = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel1(out *jwriter.Writer, in NamespaceContext) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cgroup_namespace\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.CgroupNamespace))
	}
	{
		const prefix string = ",\"ipc_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.IPCNamespace))
	}
	{
		const prefix string = ",\"net_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.NetNamespace))
	}
	{
		const prefix string = ",\"mnt_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.MntNamespace))
	}
	{
		const prefix string = ",\"pid_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.PIDNamespace))
	}
	{
		const prefix string = ",\"time_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.TimeNamespace))
	}
	{
		const prefix string = ",\"user_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UserNamespace))
	}
	{
		const prefix string = ",\"uts_namespace\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UTSNamespace))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamespaceContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamespaceContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamespaceContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamespaceContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel1(l, v)
}
func easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel2(in *jlexer.Lexer, out *CredentialsContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uid":
			out.UID = uint32(in.Uint32())
		case "gid":
			out.GID = uint32(in.Uint32())
		case "suid":
			out.SUID = uint32(in.Uint32())
		case "sgid":
			out.SGID = uint32(in.Uint32())
		case "euid":
			out.EUID = uint32(in.Uint32())
		case "egid":
			out.EGID = uint32(in.Uint32())
		case "fsuid":
			out.FSUID = uint32(in.Uint32())
		case "fsgid":
			out.FSGID = uint32(in.Uint32())
		case "secure_bits":
			out.SecureBits = uint32(in.Uint32())
		case "cap_inheritable":
			out.CapInheritable = uint64(in.Uint64())
		case "cap_permitted":
			out.CapPermitted = uint64(in.Uint64())
		case "cap_effective":
			out.CapEffective = uint64(in.Uint64())
		case "cap_bset":
			out.CapBSET = uint64(in.Uint64())
		case "cap_ambiant":
			out.CapAmbiant = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel2(out *jwriter.Writer, in CredentialsContext) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uid\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.UID))
	}
	{
		const prefix string = ",\"gid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.GID))
	}
	{
		const prefix string = ",\"suid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SUID))
	}
	{
		const prefix string = ",\"sgid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SGID))
	}
	{
		const prefix string = ",\"euid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.EUID))
	}
	{
		const prefix string = ",\"egid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.EGID))
	}
	{
		const prefix string = ",\"fsuid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FSUID))
	}
	{
		const prefix string = ",\"fsgid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FSGID))
	}
	{
		const prefix string = ",\"secure_bits\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SecureBits))
	}
	{
		const prefix string = ",\"cap_inheritable\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CapInheritable))
	}
	{
		const prefix string = ",\"cap_permitted\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CapPermitted))
	}
	{
		const prefix string = ",\"cap_effective\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CapEffective))
	}
	{
		const prefix string = ",\"cap_bset\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CapBSET))
	}
	{
		const prefix string = ",\"cap_ambiant\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CapAmbiant))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CredentialsContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CredentialsContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CredentialsContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CredentialsContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel2(l, v)
}
func easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel3(in *jlexer.Lexer, out *CgroupContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "subsystem_id":
			out.SubsystemID = CgroupSubsystemID(in.Uint32())
		case "state_id":
			out.StateID = uint32(in.Uint32())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel3(out *jwriter.Writer, in CgroupContext) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subsystem_id\":"
		out.RawString(prefix[1:])
		out.Raw((in.SubsystemID).MarshalJSON())
	}
	{
		const prefix string = ",\"state_id\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.StateID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CgroupContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CgroupContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c87105dEncodeGithubComGui774umeImdsTrackerPkgModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CgroupContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CgroupContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c87105dDecodeGithubComGui774umeImdsTrackerPkgModel3(l, v)
}
